name: MineloadPlugin
version: 0.1.0
description: Generates Minecraft server performace data in XML format.
api-version: 1.15

author: Timatooth
website: https://github.com/Timatooth/
softdepend: [JSONAPI, LWC]
main: com.timatooth.mineload.MineloadPlugin
